### ISSUE TITLE
No command 'webrf' found

### ISSUE THREAD

**Issue by marawannwh** [rynop/webrf#1]
user@ubuntu:~$ webrf setup-by-search "<my tab title>"
No command 'webrf' found, did you mean:
 Command 'weborf' from package 'weborf' (universe)
webrf: command not found

**Comment by rynop** [comment]
wbrf needs to be on your path. running 'which webrf' should produce output, if not its not on your path.  One way would be to copy it to /usr/sbin and chmod a+x /usr/sbin/webrf.

I'll update the docs to better explain this.

**Comment by marawannwh** [comment]
works now, thanks
